### ISSUE TITLE
Support demangling of rust symbols

### ISSUE THREAD

**Issue by est31** [m4b/bingrep#11]
`_ZN4core3ptr13drop_in_place17h86fdc7b11166c663E` is not nice to read. Could bingrep demangle it?

**Comment by m4b** [comment]
@est31 Yes, someone just simply needs to add rustc_demangle to the dependencies; see https://github.com/m4b/cargo-sym for an example of this, e.g.: https://github.com//m4b/cargo-sym/blob/9622ffb7217d565b03bf90cba19df3bc781c8b0f/src/symbol.rs#L19

I believe simply adding it here would resolve the issue: https://github.com//m4b/bingrep/blob/21adcb69fbe6957fa4d2495d9027f6881a6cde54/src/main.rs#L57

But needs testing.
