### ISSUE TITLE
inconsistent results from ldd for library dependencies

### ISSUE THREAD

**Issue by hongxuchen** [m4b/bingrep#18]
I compiled the following source code on Linux with gcc.

```c
// test.c
#include <stdio.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
int main(void) {
    fd_set rfds;
    struct timeval tv;
    int retval;
    /* Watch stdin (fd 0) to see when it has input. */
    FD_ZERO(&rfds);
    FD_SET(0, &rfds);
    /* Wait up to five seconds. */
    tv.tv_sec = 5;
    tv.tv_usec = 0;
    retval = select(1, &rfds, NULL, NULL, &tv);
    /* Don’t rely on the value of tv now! */
    if (retval == -1)
        perror("select()");
    else if (retval)
        printf("Data is available now.\n");
        /* FD_ISSET(0, &rfds) will be true. */
    else
        printf("No data within five seconds.\n");
    return 0;
}
```
```
gcc test.c -fsanitize=address
```

`ldd a.out` gives

```
        linux-vdso.so.1 =>  (0x00007ffec89a5000)
        libasan.so.2 => /usr/lib/x86_64-linux-gnu/libasan.so.2 (0x00007fde56b6a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fde567a0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fde56583000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fde5637f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fde56076000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fde55e5f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fde57ad7000)
```

But bingrep tells only
```
...
Libraries(2):
    libasan.so.2
       libc.so.6
...
```

While I can understand libraries like `linux-vdso.so.1` can be omitted, I think `libpthread.so.0` should at least (only sure about ` libm.so.6` and others) exist in the dependence list.

**Comment by m4b** [comment]
ldd prints every loaded dynamic library, which includes every deps libs, etc. 

Eg it flattens the dynamic library tree. 

Your c program only depends on libc, and I guess your gcc install also adds libasan for you. 

Try compiling with:

```
gcc -lpthread -lm test.c -fsanitize=address
```

And you should see the new libraries explicitly burned into the immediate deps of test

**Comment by hongxuchen** [comment]
@m4b but when even deliberately adding `-lpthread -lm` does not change the output of bingrep for me.
I guess you are right as to `ldd`'s flatten behavior though.

**Comment by m4b** [comment]
Yea whether gcc will add the libraries if you dont use a function from them probably depends on gcc version etc.
