### ISSUE TITLE
Create git tag for releases

### ISSUE THREAD

**Issue by xu-cheng** [m4b/bingrep#24]
I'd like to package this tool in Homebrew. However, like many other package managers, a tag release is required. As such, the source code for each versions can be downloaded through some url. 

I noticed there are version bumps in `Cargo.toml`, so all you need to do is to create git tag (or even better creating Github Release).

Thanks.

**Comment by m4b** [comment]
Cool! I’ll try to get to this tonight; if you don’t hear from me, feel free to aggressively ping me :)

I just need to push tags right?

`git push —tags`

And I’ll just google about how to do github release; thanks for the issue !

**Comment by bjorn3** [comment]
You can go to https://github.com/m4b/bingrep/releases and click on the create new release button to create a new gh release and at the same time the associated label. You can paste the commit hash as target.

**Comment by xu-cheng** [comment]
Yes, you can tag the commit using `git tag <tag-name> <commit>` then `git push --tags` to push them.

Alternatively, you can use Github UI at https://github.com/m4b/bingrep/releases.

**Comment by m4b** [comment]
Ok I pushed 0.8.1 and it’s showing up on the releases page; so I have to do anything else here ?

And thanks for packaging it up ! :)

**Comment by xu-cheng** [comment]
Thanks. I have submit a PR to homebrew to package this tool: https://github.com/Homebrew/homebrew-core/pull/46712/

**Comment by xu-cheng** [comment]
FYI, the package has been accepted. bingrep can now be installed through `brew install bingrep` on macOS.

**Comment by m4b** [comment]
Great thanks for your work in making that happen !
