### ISSUE TITLE
Outdated Cargo.lock file?

### ISSUE THREAD

**Issue by carlocab** [m4b/bingrep#29]
bingrep is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68089

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for bingrep on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

Related: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by m4b** [comment]
What is the specific error exactly ? Anyway I updated lock file, let me know if there are any other issues !

**Comment by carlocab** [comment]
I didn't get the chance to look at the specific error message, unfortunately, as I was also looking at about a hundred other packages that use Rust to build.

All I know is that `bingrep` fails to build with `cargo install --locked`, but does not fail when the `--locked` flag was dropped. It's a very crude test, but it's proved to be correct a number of times already.

Yes, I see you've updated the lock file in https://github.com/m4b/bingrep/commit/b2aa67acb94af86447c3d4758f9b61e60164f722. Any chance you could also tag the release of 0.8.4 here on GitHub?

**Comment by m4b** [comment]
ok i tagged it 0.8.4

**Comment by carlocab** [comment]
Great! It builds on Apple M1 now: https://github.com/Homebrew/homebrew-core/pull/68743/checks?check_run_id=1678656566

Thanks so much; you've been very helpful.
