### ISSUE TITLE
PE/PE+ colorized backend

### ISSUE THREAD

**Issue by m4b** [m4b/bingrep#3]
Should be easy; can copy paste some of the closure color functions until they're refactored into nicer functions.

As for exact display, can discuss, see what works best

**Comment by m4b** [comment]
Printer functions are all refactored and reusable; if anyone is watching and wants to give this a shot, I will definitely give any tips about how to do this, answer any questions, etc, but I don't have time to personally start on this this right now.

**Comment by koutheir** [comment]
Hi @m4b, this is my first attempt at fixing this issue: [bingrep.zip](https://github.com/m4b/bingrep/files/7983872/bingrep.zip). Can you tell me what you think of it? If you deem it reasonable, then I can create a pull request.

**Comment by m4b** [comment]
This is awesome, pull request would be great! The output looks nice and clean; just fyi though, if we do merge it, I'll probably forward bugs to you since you would be the primary author of that component :)

**Comment by koutheir** [comment]
> This is awesome, pull request would be great!

I'll do that soon.

> just fyi though, if we do merge it, I'll probably forward bugs to you since you would be the primary author of that component :)

That is okay, at least in the near future.
