### ISSUE TITLE
Potential bug with ELF binaries

### ISSUE THREAD

**Issue by koutheir** [m4b/bingrep#33]
In [src/format_elf.rs:286](https://github.com/m4b/bingrep/blob/9e84be52eec8fd9c2be3b3d939a80cde75e2fdb6/src/format_elf.rs#L286), the condition expression `shflags & flag == flag` seems wrong:

```rust
                    let mut flags = String::new();
                    for flag in &section_header::SHF_FLAGS {
                        let flag = *flag;
/* HERE */              if shflags & flag == flag {
                            flags += &section_header::shf_to_str(flag).to_string().split_off(4);
                            flags += " ";
                        }
                    }
                    Cell::new(&flags).style_spec("lbW")
```

The condition **always** evaluates to true. This change was introduced by [commit #34c38277abe8305a9070d9a05e9d8ddfe354521d](https://github.com/m4b/bingrep/commit/34c38277abe8305a9070d9a05e9d8ddfe354521d).

@m4b, could you please double-check this code to fix it.

**Comment by bjorn3** [comment]
Are you sure it always evaluates to true. To me it looks like it only evaluates to true if the specific flag is set.

**Comment by koutheir** [comment]
You're right. The operator `&` has a stronger precedence than `==`.
